#!/bin/awk -f
# This script gets the data between two segments of tracking
# file name should be passed as argument
BEGIN { IGNORECASE=1; print "  getting data from file..."}
{
  if($1=="#segment") {
    flname=$6;\
#    print "track"$6;\
    print "    segment "flname"\tfound. Creating file track"flname" ...";
  }else{print $0 >> "track"flname;}\
}
END { print "  all done. Adios"}
