#!/bin/awk -f
# This script gets the data between two segments of tracking
BEGIN { IGNORECASE=1; }
{
  if($1=="#segment") {
    flname=$6;\
#  print "track"$6;\
 }else{print $0 >> "track"flname}
}
END { print "  all done. Adios"}

